spring:
  # 通用数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/permission?useUnicode=true&characterEncoding=UTF-8&autoReconnet=true
    username: root
    password: 123456
    # Hikari 数据源专用配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  # JPA相关配置
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  # es
#  data:
#    elasticsearch:
#      cluster-name: 127.0.0.1:9300
#      cluster-nodes: my-application
  # mvc
  mvc:
    static-path-pattern: /**

  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: static/**

  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss